import joblib
import streamlit as st
from scipy.sparse import csr_matrix, hstack
from streamlit_extras.colored_header import colored_header
from streamlit_extras.let_it_rain import rain
import numpy as np
from preprocess import preprocess_sample


# Hàm dự đoán
def predict_isdga(features, model):
    prediction = model.predict(features)
    return prediction[0]


def predict_dga_family(features, model):
    prediction = model.predict(features)
    probability = model.predict_proba(features)
    return prediction[0], max(probability[0])


# Giao diện Streamlit
def main():
    st.set_page_config(
        page_title="DGA Domain Detection", page_icon="🌐", layout="centered"
    )

    colored_header(
        label="DGA Domain Detection",
        description="Check if a domain is legitimate or generated by malware.",
        color_name="blue-70",
    )

    # Sidebar
    with st.sidebar:
        # st.image(
        #     "https://upload.wikimedia.org/wikipedia/commons/8/83/DNS_Server.gif",
        #     use_column_width=True,
        # )
        st.write(
            "This tool helps detect whether a domain is safe or a potential threat."
        )
        st.markdown("**Instructions:**")
        st.markdown("1. Enter a full domain name in the input field.")
        st.markdown("2. Click **Predict** to analyze the domain.")
        st.markdown("3. View the results with confidence score.")

    # Load models
    try:
        model_sc = joblib.load("logreg_subclass.pkl")
        model_isdga = joblib.load("logreg_isdga.pkl")
        le = joblib.load("le.pkl")
        # tfidf_host_sc = joblib.load("RF_subclass/tfidf_host_sc.pkl")
        # tfidf_host_isdga = joblib.load("RF_isdga/tfidf_host_isdga.pkl")
        st.success("✅ Models loaded successfully!")
    except FileNotFoundError:
        st.error("⚠️ Model files not found. Please train and save the models first.")
        return

    # Nhập liệu từ người dùng
    host_input = st.text_input("Enter domain name:", "6xzxsw3sokvg1tc752y1a6p0af.com")

    # Nút dự đoán
    if st.button("🔍 Predict"):
        if host_input:
            Xisdga, Xsc = preprocess_sample(host_input)
            isdga_pred = predict_isdga(Xisdga, model_isdga)
            sc_pred, probability = predict_dga_family(Xsc, model_sc)

            st.write("### 🔎 Analysis Result")
            if isdga_pred == 1:
                st.success("✅ **LEGITIMATE DOMAIN**")
            else:
                st.error("⚠️ **DGA DETECTED!**")
                rain(emoji="⚠️", font_size=30, falling_speed=3, animation_length=2)

            st.write(f"**Domain:** `{host_input.split('.')[0]}`")
            st.write(
                f"**Result:** `{"Legitimate" if isdga_pred == 1 else "DGA"}` - {isdga_pred}"
            )
            st.write(
                f"**Family:** `{le.inverse_transform(np.array([sc_pred]))[0]} - {sc_pred}`"
            )
            st.write(f"**Confidence:** `{probability:.2f}`")
        else:
            st.warning("⚠️ Please enter a valid domain.")


if __name__ == "__main__":
    main()
